<?php

use Illuminate\Database\Seeder;
use App\Models\Paisesmoodle;

class PaisesMoodleTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'AD';
        $paisesmoodle->nombre = 'Andorra';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'AE';
        $paisesmoodle->nombre = 'United Arab Emirates';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'AF';
        $paisesmoodle->nombre = 'Afghanistan';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'AG';
        $paisesmoodle->nombre = 'Antigua and Barbuda';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'AI';
        $paisesmoodle->nombre = 'Anguilla';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'AL';
        $paisesmoodle->nombre = 'Albania';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'AM';
        $paisesmoodle->nombre = 'Armenia';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'AO';
        $paisesmoodle->nombre = 'Angola';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'AQ';
        $paisesmoodle->nombre = 'Antarctica';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'AR';
        $paisesmoodle->nombre = 'Argentina';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'AS';
        $paisesmoodle->nombre = 'American Samoa';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'AT';
        $paisesmoodle->nombre = 'Austria';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'AU';
        $paisesmoodle->nombre = 'Australia';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'AW';
        $paisesmoodle->nombre = 'Aruba';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'AX';
        $paisesmoodle->nombre = 'Åland Islands';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'AZ';
        $paisesmoodle->nombre = 'Azerbaijan';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'BA';
        $paisesmoodle->nombre = 'Bosnia and Herzegovina';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'BB';
        $paisesmoodle->nombre = 'Barbados';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'BD';
        $paisesmoodle->nombre = 'Bangladesh';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'BE';
        $paisesmoodle->nombre = 'Belgium';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'BF';
        $paisesmoodle->nombre = 'Burkina Faso';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'BG';
        $paisesmoodle->nombre = 'Bulgaria';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'BH';
        $paisesmoodle->nombre = 'Bahrain';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'BI';
        $paisesmoodle->nombre = 'Burundi';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'BJ';
        $paisesmoodle->nombre = 'Benin';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'BL';
        $paisesmoodle->nombre = 'Saint Barthélemy';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'BM';
        $paisesmoodle->nombre = 'Bermuda';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'BN';
        $paisesmoodle->nombre = 'Brunei Darussalam';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'BO';
        $paisesmoodle->nombre = 'Bolivia (Plurinational State of)';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'BQ';
        $paisesmoodle->nombre = 'Bonaire, Sint Eustatius and Saba';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'BR';
        $paisesmoodle->nombre = 'Brazil';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'BS';
        $paisesmoodle->nombre = 'Bahamas';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'BT';
        $paisesmoodle->nombre = 'Bhutan';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'BV';
        $paisesmoodle->nombre = 'Bouvet Island';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'BW';
        $paisesmoodle->nombre = 'Botswana';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'BY';
        $paisesmoodle->nombre = 'Belarus';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'BZ';
        $paisesmoodle->nombre = 'Belize';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'CA';
        $paisesmoodle->nombre = 'Canada';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'CC';
        $paisesmoodle->nombre = 'Cocos (Keeling) Islands';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'CD';
        $paisesmoodle->nombre = 'Congo (the Democratic Republic of the)';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'CF';
        $paisesmoodle->nombre = 'Central African Republic';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'CG';
        $paisesmoodle->nombre = 'Congo';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'CH';
        $paisesmoodle->nombre = 'Switzerland';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'CI';
        $paisesmoodle->nombre = 'Côte d\'Ivoire';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'CK';
        $paisesmoodle->nombre = 'Cook Islands';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'CL';
        $paisesmoodle->nombre = 'Chile';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'CM';
        $paisesmoodle->nombre = 'Cameroon';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'CN';
        $paisesmoodle->nombre = 'China';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'CO';
        $paisesmoodle->nombre = 'Colombia';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'CR';
        $paisesmoodle->nombre = 'Costa Rica';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'CU';
        $paisesmoodle->nombre = 'Cuba';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'CV';
        $paisesmoodle->nombre = 'Cabo Verde';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'CW';
        $paisesmoodle->nombre = 'Curaçao';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'CX';
        $paisesmoodle->nombre = 'Christmas Island';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'CY';
        $paisesmoodle->nombre = 'Cyprus';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'CZ';
        $paisesmoodle->nombre = 'Czechia';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'DE';
        $paisesmoodle->nombre = 'Germany';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'DJ';
        $paisesmoodle->nombre = 'Djibouti';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'DK';
        $paisesmoodle->nombre = 'Denmark';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'DM';
        $paisesmoodle->nombre = 'Dominica';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'DO';
        $paisesmoodle->nombre = 'Dominican Republic';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'DZ';
        $paisesmoodle->nombre = 'Algeria';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'EC';
        $paisesmoodle->nombre = 'Ecuador';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'EE';
        $paisesmoodle->nombre = 'Estonia';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'EG';
        $paisesmoodle->nombre = 'Egypt';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'EH';
        $paisesmoodle->nombre = 'Western Sahara';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'ER';
        $paisesmoodle->nombre = 'Eritrea';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'ES';
        $paisesmoodle->nombre = 'Spain';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'ET';
        $paisesmoodle->nombre = 'Ethiopia';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'FI';
        $paisesmoodle->nombre = 'Finland';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'FJ';
        $paisesmoodle->nombre = 'Fiji';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'FK';
        $paisesmoodle->nombre = 'Falkland Islands (Malvinas)';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'FM';
        $paisesmoodle->nombre = 'Micronesia (Federated States of)';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'FO';
        $paisesmoodle->nombre = 'Faroe Islands';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'FR';
        $paisesmoodle->nombre = 'France';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'GA';
        $paisesmoodle->nombre = 'Gabon';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'GB';
        $paisesmoodle->nombre = 'United Kingdom';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'GD';
        $paisesmoodle->nombre = 'Grenada';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'GE';
        $paisesmoodle->nombre = 'Georgia';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'GF';
        $paisesmoodle->nombre = 'French Guiana';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'GG';
        $paisesmoodle->nombre = 'Guernsey';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'GH';
        $paisesmoodle->nombre = 'Ghana';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'GI';
        $paisesmoodle->nombre = 'Gibraltar';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'GL';
        $paisesmoodle->nombre = 'Greenland';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'GM';
        $paisesmoodle->nombre = 'Gambia';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'GN';
        $paisesmoodle->nombre = 'Guinea';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'GP';
        $paisesmoodle->nombre = 'Guadeloupe';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'GQ';
        $paisesmoodle->nombre = 'Equatorial Guinea';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'GR';
        $paisesmoodle->nombre = 'Greece';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'GS';
        $paisesmoodle->nombre = 'South Georgia and the South Sandwich Islands';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'GT';
        $paisesmoodle->nombre = 'Guatemala';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'GU';
        $paisesmoodle->nombre = 'Guam';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'GW';
        $paisesmoodle->nombre = 'Guinea-Bissau';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'GY';
        $paisesmoodle->nombre = 'Guyana';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'HK';
        $paisesmoodle->nombre = 'Hong Kong';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'HM';
        $paisesmoodle->nombre = 'Heard Island and McDonald Islands';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'HN';
        $paisesmoodle->nombre = 'Honduras';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'HR';
        $paisesmoodle->nombre = 'Croatia';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'HT';
        $paisesmoodle->nombre = 'Haiti';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'HU';
        $paisesmoodle->nombre = 'Hungary';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'ID';
        $paisesmoodle->nombre = 'Indonesia';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'IE';
        $paisesmoodle->nombre = 'Ireland';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'IL';
        $paisesmoodle->nombre = 'Israel';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'IM';
        $paisesmoodle->nombre = 'Isle of Man';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'IN';
        $paisesmoodle->nombre = 'India';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'IO';
        $paisesmoodle->nombre = 'British Indian Ocean Territory';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'IQ';
        $paisesmoodle->nombre = 'Iraq';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'IR';
        $paisesmoodle->nombre = 'Iran (Islamic Republic of)';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'IS';
        $paisesmoodle->nombre = 'Iceland';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'IT';
        $paisesmoodle->nombre = 'Italy';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'JE';
        $paisesmoodle->nombre = 'Jersey';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'JM';
        $paisesmoodle->nombre = 'Jamaica';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'JO';
        $paisesmoodle->nombre = 'Jordan';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'JP';
        $paisesmoodle->nombre = 'Japan';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'KE';
        $paisesmoodle->nombre = 'Kenya';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'KG';
        $paisesmoodle->nombre = 'Kyrgyzstan';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'KH';
        $paisesmoodle->nombre = 'Cambodia';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'KI';
        $paisesmoodle->nombre = 'Kiribati';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'KM';
        $paisesmoodle->nombre = 'Comoros';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'KN';
        $paisesmoodle->nombre = 'Saint Kitts and Nevis';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'KP';
        $paisesmoodle->nombre = 'Korea (the Democratic People\'s Republic of)';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'KR';
        $paisesmoodle->nombre = 'Korea (the Republic of)';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'KW';
        $paisesmoodle->nombre = 'Kuwait';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'KY';
        $paisesmoodle->nombre = 'Cayman Islands';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'KZ';
        $paisesmoodle->nombre = 'Kazakhstan';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'LA';
        $paisesmoodle->nombre = 'Lao People\'s Democratic Republic';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'LB';
        $paisesmoodle->nombre = 'Lebanon';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'LC';
        $paisesmoodle->nombre = 'Saint Lucia';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'LI';
        $paisesmoodle->nombre = 'Liechtenstein';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'LK';
        $paisesmoodle->nombre = 'Sri Lanka';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'LR';
        $paisesmoodle->nombre = 'Liberia';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'LS';
        $paisesmoodle->nombre = 'Lesotho';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'LT';
        $paisesmoodle->nombre = 'Lithuania';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'LU';
        $paisesmoodle->nombre = 'Luxembourg';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'LV';
        $paisesmoodle->nombre = 'Latvia';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'LY';
        $paisesmoodle->nombre = 'Libya';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'MA';
        $paisesmoodle->nombre = 'Morocco';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'MC';
        $paisesmoodle->nombre = 'Monaco';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'MD';
        $paisesmoodle->nombre = 'Moldova (the Republic of)';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'ME';
        $paisesmoodle->nombre = 'Montenegro';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'MF';
        $paisesmoodle->nombre = 'Saint Martin (French part)';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'MG';
        $paisesmoodle->nombre = 'Madagascar';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'MH';
        $paisesmoodle->nombre = 'Marshall Islands';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'MK';
        $paisesmoodle->nombre = 'North Macedonia';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'ML';
        $paisesmoodle->nombre = 'Mali';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'MM';
        $paisesmoodle->nombre = 'Myanmar';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'MN';
        $paisesmoodle->nombre = 'Mongolia';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'MO';
        $paisesmoodle->nombre = 'Macao';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'MP';
        $paisesmoodle->nombre = 'Northern Mariana Islands';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'MQ';
        $paisesmoodle->nombre = 'Martinique';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'MR';
        $paisesmoodle->nombre = 'Mauritania';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'MS';
        $paisesmoodle->nombre = 'Montserrat';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'MT';
        $paisesmoodle->nombre = 'Malta';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'MU';
        $paisesmoodle->nombre = 'Mauritius';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'MV';
        $paisesmoodle->nombre = 'Maldives';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'MW';
        $paisesmoodle->nombre = 'Malawi';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'MX';
        $paisesmoodle->nombre = 'Mexico';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'MY';
        $paisesmoodle->nombre = 'Malaysia';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'MZ';
        $paisesmoodle->nombre = 'Mozambique';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'NA';
        $paisesmoodle->nombre = 'Namibia';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'NC';
        $paisesmoodle->nombre = 'New Caledonia';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'NE';
        $paisesmoodle->nombre = 'Niger';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'NF';
        $paisesmoodle->nombre = 'Norfolk Island';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'NG';
        $paisesmoodle->nombre = 'Nigeria';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'NI';
        $paisesmoodle->nombre = 'Nicaragua';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'NL';
        $paisesmoodle->nombre = 'Netherlands';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'NO';
        $paisesmoodle->nombre = 'Norway';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'NP';
        $paisesmoodle->nombre = 'Nepal';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'NR';
        $paisesmoodle->nombre = 'Nauru';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'NU';
        $paisesmoodle->nombre = 'Niue';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'NZ';
        $paisesmoodle->nombre = 'New Zealand';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'OM';
        $paisesmoodle->nombre = 'Oman';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'PA';
        $paisesmoodle->nombre = 'Panama';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'PE';
        $paisesmoodle->nombre = 'Peru';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'PF';
        $paisesmoodle->nombre = 'French Polynesia';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'PG';
        $paisesmoodle->nombre = 'Papua New Guinea';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'PH';
        $paisesmoodle->nombre = 'Philippines';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'PK';
        $paisesmoodle->nombre = 'Pakistan';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'PL';
        $paisesmoodle->nombre = 'Poland';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'PM';
        $paisesmoodle->nombre = 'Saint Pierre and Miquelon';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'PN';
        $paisesmoodle->nombre = 'Pitcairn';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'PR';
        $paisesmoodle->nombre = 'Puerto Rico';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'PS';
        $paisesmoodle->nombre = 'Palestine, State of';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'PT';
        $paisesmoodle->nombre = 'Portugal';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'PW';
        $paisesmoodle->nombre = 'Palau';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'PY';
        $paisesmoodle->nombre = 'Paraguay';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'QA';
        $paisesmoodle->nombre = 'Qatar';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'RE';
        $paisesmoodle->nombre = 'Réunion';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'RO';
        $paisesmoodle->nombre = 'Romania';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'RS';
        $paisesmoodle->nombre = 'Serbia';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'RU';
        $paisesmoodle->nombre = 'Russian Federation';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'RW';
        $paisesmoodle->nombre = 'Rwanda';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'SA';
        $paisesmoodle->nombre = 'Saudi Arabia';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'SB';
        $paisesmoodle->nombre = 'Solomon Islands';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'SC';
        $paisesmoodle->nombre = 'Seychelles';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'SD';
        $paisesmoodle->nombre = 'Sudan';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'SE';
        $paisesmoodle->nombre = 'Sweden';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'SG';
        $paisesmoodle->nombre = 'Singapore';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'SH';
        $paisesmoodle->nombre = 'Saint Helena, Ascension and Tristan da Cunha';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'SI';
        $paisesmoodle->nombre = 'Slovenia';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'SJ';
        $paisesmoodle->nombre = 'Svalbard and Jan Mayen';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'SK';
        $paisesmoodle->nombre = 'Slovakia';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'SL';
        $paisesmoodle->nombre = 'Sierra Leone';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'SM';
        $paisesmoodle->nombre = 'San Marino';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'SN';
        $paisesmoodle->nombre = 'Senegal';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'SO';
        $paisesmoodle->nombre = 'Somalia';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'SR';
        $paisesmoodle->nombre = 'Suriname';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'SS';
        $paisesmoodle->nombre = 'South Sudan';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'ST';
        $paisesmoodle->nombre = 'Sao Tome and Principe';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'SV';
        $paisesmoodle->nombre = 'El Salvador';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'SX';
        $paisesmoodle->nombre = 'Sint Maarten (Dutch part)';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'SY';
        $paisesmoodle->nombre = 'Syrian Arab Republic';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'SZ';
        $paisesmoodle->nombre = 'Eswatini';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'TC';
        $paisesmoodle->nombre = 'Turks and Caicos Islands';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'TD';
        $paisesmoodle->nombre = 'Chad';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'TF';
        $paisesmoodle->nombre = 'French Southern Territories';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'TG';
        $paisesmoodle->nombre = 'Togo';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'TH';
        $paisesmoodle->nombre = 'Thailand';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'TJ';
        $paisesmoodle->nombre = 'Tajikistan';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'TK';
        $paisesmoodle->nombre = 'Tokelau';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'TL';
        $paisesmoodle->nombre = 'Timor-Leste';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'TM';
        $paisesmoodle->nombre = 'Turkmenistan';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'TN';
        $paisesmoodle->nombre = 'Tunisia';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'TO';
        $paisesmoodle->nombre = 'Tonga';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'TR';
        $paisesmoodle->nombre = 'Turkey';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'TT';
        $paisesmoodle->nombre = 'Trinidad and Tobago';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'TV';
        $paisesmoodle->nombre = 'Tuvalu';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'TW';
        $paisesmoodle->nombre = 'Taiwan';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'TZ';
        $paisesmoodle->nombre = 'Tanzania, the United Republic of';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'UA';
        $paisesmoodle->nombre = 'Ukraine';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'UG';
        $paisesmoodle->nombre = 'Uganda';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'UM';
        $paisesmoodle->nombre = 'United States Minor Outlying Islands';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'US';
        $paisesmoodle->nombre = 'United States';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'UY';
        $paisesmoodle->nombre = 'Uruguay';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'UZ';
        $paisesmoodle->nombre = 'Uzbekistan';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'VA';
        $paisesmoodle->nombre = 'Holy See';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'VC';
        $paisesmoodle->nombre = 'Saint Vincent and the Grenadines';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'VE';
        $paisesmoodle->nombre = 'Venezuela (Bolivarian Republic of)';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'VG';
        $paisesmoodle->nombre = 'Virgin Islands (British)';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'VI';
        $paisesmoodle->nombre = 'Virgin Islands (U.S.)';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'VN';
        $paisesmoodle->nombre = 'Viet Nam';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'VU';
        $paisesmoodle->nombre = 'Vanuatu';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'WF';
        $paisesmoodle->nombre = 'Wallis and Futuna';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'WS';
        $paisesmoodle->nombre = 'Samoa';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'YE';
        $paisesmoodle->nombre = 'Yemen';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'YT';
        $paisesmoodle->nombre = 'Mayotte';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'ZA';
        $paisesmoodle->nombre = 'South Africa';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'ZM';
        $paisesmoodle->nombre = 'Zambia';
        $paisesmoodle->save();
        $paisesmoodle = new PaisesMoodle();
        $paisesmoodle->codigo = 'ZW';
        $paisesmoodle->nombre = 'Zimbabwe';
        $paisesmoodle->save();
    }
}
